import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';

import fire from '../config/firebaseConfig';

export default function Home () {
  const [name, setName] = useState();
  useEffect( () => {
    fetch( '/api/hello' )
      .then( res => res.json() )
      .then( data => {
        setName( data.name );
      } );
  }, [] );

  useEffect( () => {
    const db = fire.firestore();
    db.collection( "jams" ).get().then( ( querySnapshot ) => {
      querySnapshot.forEach( ( doc ) => {
        const jam = doc.data();
        jam.statements = [];
        db.collection( "jams" )
          .doc( doc.id )
          .collection( "statements" ).get().then( query => {
            query.forEach( statement => jam.statements.push( statement.id ) )
          } )
        console.log( jam );
      } );
    } );

    const allStuff = []
    db.collection( "participants" ).doc( 'BlNS4ZNBIJhEt1GJqEvm' ).collection( "votes" ).
      get().then( query => query.forEach( votes => allStuff.push( votes.data() ) ) )
    console.log( allStuff )
  }, [] );

  // get all the statements a participant has voted on 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {name}!
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
